version: '3'
services:    
  pgsql:
      image: postgres
      container_name: db_pgsql_ccca15
      ports:
          - '35432:5432'
      expose:
          - '35432'
      environment:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: ccca_15